### PR TITLE
sentry-java v-next

### PR DESCRIPTION
**Pull request by bruno-garcia**
base PR when bulding `sentry-java` based on this repository.

If the PR isn't adding a breaking change or won't negativily affect the Android SDK it case it can target `master` instead

### CODE REVIEW

**Comment by bruno-garcia** [comment]
> This pull request **introduces 1 alert** when merging [68c7ceb](https://github.com/getsentry/sentry-android/commit/68c7ceb3f1446c3fb608182dd7bded36f15edefd) into [42d74d9](https://github.com/getsentry/sentry-android/commit/42d74d9f4d90ebfb92a009c04b78cb35eb502762) - [view on LGTM.com](https://lgtm.com/projects/g/getsentry/sentry-android/rev/pr-e1d62f7b5fe931f8c8e2d5a353a63962862185ca)
> 
> **new alerts:**
> 
>     * 1 for Disabled Spring CSRF protection

@maciejwalkowiak LGTM check failed on the last PR, so we misse this ^

**Comment by maciejwalkowiak** [comment]
Looks like adding `@SuppressWarnings("lgtm[java/spring-disabled-csrf-protection]")` helps with hiding error at lgtm.com but not from getting an alert :/

**Comment by bruno-garcia** [comment]
Let's ignore it for now. We might have to open an ticket with them later

**Comment by bruno-garcia** [comment]
I wish @lgtm-com would respect the suppression and stop reposing this every time.
It's a bloddy sample LGTM, go home.

**Comment by bruno-garcia** [comment]
CI is unhappy

```
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    /Users/runner/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.4.0/e3765b66f0610afc92053ff1a93a87a544fca2b/kotlin-stdlib-jdk8-1.4.0.jar (version 1.4)
    /Users/runner/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.3.72/3adfc2f4ea4243e01204be8081fe63bde6b12815/kotlin-stdlib-jdk7-1.3.72.jar (version 1.3)
    /Users/runner/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.3.72/8032138f12c0180bc4e51fe139d4c52b46db6109/kotlin-stdlib-1.3.72.jar (version 1.3)
    /Users/runner/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.3.72/6ca8bee3d88957eaaaef077c41c908c9940492d8/kotlin-stdlib-common-1.3.72.jar (version 1.3)
```

**Comment by bruno-garcia** [comment]
I've pulled 3.0.0 into it, which pulled master earlier today.
Changing base to master again.

Once CI is green we can merge this.

**Pull request merged**
