### PR TITLE
Make SentryEvent.getThrowable() public.

### PR DESCRIPTION
**Pull request by metlos**
## :loudspeaker: Type of change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring

## :scroll: Description
`$TITLE`

## :bulb: Motivation and Context
Custom event processors might want to access it the same way the main event processor. It also makes testing easier/possible (to make sure that integrations set it properly).

## :green_heart: How did you test it?
NA

## :pencil: Checklist
- [x] I reviewed submitted code
- [ ] I added tests to verify changes
- [x] All tests passing

### CODE REVIEW

**Comment by bruno-garcia** [comment]
It was made internal on purpose, because once we get this public, it's public API. We'd like to review the use cases before doing that and think this through since `SentryEvent` is supposed to hold the protocol and we're using it to hold extra data while processing the event.

It's useful (more so than just `SentryException`) since a user can have custom code to handle their own exception types. You could read the extra fields of your customer exception and augment the event.

What would be the use cases you already have in mind @metlos?

**Comment by bruno-garcia** [comment]
@marandaneto: @dilbernd brought this up again. 

We either need to reconsider how we do things here (i.e: process the exception inside `captureException` like other SDKs) or make this method public.

I'd rather make this public. What do you folks thing?

**Comment by dilbernd** [comment]
I don’t need it for prod code, I was just porting test code from @metlos into the new structure.

I’ll go a different route then. It was package private, I’ll just create a proxy in the test sources in the same package and give that a public getter.

If I have an actual direct need for it I’ll revisit is later but let’s put it back again for now.

**Comment by bruno-garcia** [comment]
Sounds good. We'll close this PR then.
Thanks

**Pull request closed without merging**
