### PR TITLE
Add method to add breadcrumb with string parameter.

### PR DESCRIPTION
**Pull request by maciejwalkowiak**
## :loudspeaker: Type of change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring

## :scroll: Description

Add method to add breadcrumb with string parameter.

## :bulb: Motivation and Context

See https://github.com/getsentry/sentry-android/pull/499#discussion_r462614172

## :green_heart: How did you test it?
There's a unit test.

## :pencil: Checklist

- [x] I reviewed submitted code
- [x] I added tests to verify changes
- [x] All tests passing
- [x] No breaking changes

### CODE REVIEW

**Comment by bruno-garcia** [comment]
Oh, what about this also going to `master`?

**Comment by maciejwalkowiak** [comment]
I'm good if it goes to `master`. I took today's discussion of not breaking Android build seriously 🙂  I've just switched base branch to master.

**Comment by bruno-garcia** [comment]
Makes sense to be on the safe side.

This is just an overload so not a breaking change though
For sure Android users can take advantage also, so would be nice.

I believe the main concern are things that would need to be tested on different Android version (yup) to make sure things continue to work. Because, Android.

Things like this overload IMO are safe and will make it simpler later for us to merge things from the java branch and master since a lot of code **not ok** to merge into master will follow.

@marandaneto thoughts?

**Comment by marandaneto** [comment]
> Makes sense to be on the safe side.
> 
> This is just an overload so not a breaking change though
> For sure Android users can take advantage also, so would be nice.
> 
> I believe the main concern are things that would need to be tested on different Android version (yup) to make sure things continue to work. Because, Android.
> 
> Things like this overload IMO are safe and will make it simpler later for us to merge things from the java branch and master since a lot of code **not ok** to merge into master will follow.
> 
> @marandaneto thoughts?

yep, agreed, it's just an overload, things like this are LGTM

**Comment by maciejwalkowiak** [comment]
Closed in favour of #501.

**Pull request closed without merging**
